AllCops:
  TargetRubyVersion: 3.1

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - app/jobs/update_sparta_state_job.rb

Metrics/MethodLength:
  Exclude:
    - app/jobs/update_sparta_state_job.rb

Metrics/ClassLength:
  Exclude:
    - app/jobs/update_sparta_state_job.rb

Metrics/ParameterLists:
  Max: 8
