dist: focal
language: ruby
rvm:
- 3.3.3
branches:
  only:
  - develop
  - staging
  - master
  - aaaaaaaaaa
before_install:
- gem install bundler -v 2.6.2
install:
  - bundle install
script:
  - bundle exec rubocop
  - bundle exec brakeman

